### ISSUE TITLE
Using get_face_image

### ISSUE THREAD

**Issue by steview** [jrm2194/betaface#1]
Hi @jrm2194 

I'm trying to use the get_face_image method of the API request.

The response has the following keys: ["int_response", "string_response", "face_image", "face_info", "uid"].

The face_image key seems to be an array of integers?

The [docs](https://betafaceapi.com/api_examples/GetFaceImage_response.xml) seem to suggest I should expect Base64?

Any idea what format it's in and how I should use it?

Thanks.

**Comment by jrm2194** [comment]
Hi Steview,

It seems that's what the API returns. If you use their demo page here: [https://betafaceapi.com/forms_json.html](https://betafaceapi.com/forms_json.html)

You will also get an array of integers. I'm directly going to ask the CTO of betaface and come back to you ASAP.

J

**Comment by jrm2194** [comment]
Please find below the official response from betaface:

`Currently Json responses endpoint returns array of bytes, Xml endpoint returns Base64`

The Gem is using the JSON responses.

**Comment by steview** [comment]
Hi @jrm2194.

Any idea how to convert it to usable image data (jpg I assume)?

I've tried the following with no joy:

``` ruby
api = Betaface::Api.new(ENV['BETAFACE_API_KEY'], ENV['BETAFACE_API_SECRET'])
face_image = api.get_face_image(face['uid'])
file_path = Rails.root.join('tmp', "(A)#{face['uid']}.jpg")
File.open(file_path, 'wb') do |file|
   file.write [face_image['face_image'].join].pack('A')
end
```

It creates files that are not readable.

The [pack](http://www.rubydoc.info/stdlib/core/Array%3Apack) method take a directive, I've tried the following:

'A', 'a', 'Z', 'B', 'b', 'H', 'h', 'u', 'M', 'm', 'P', 'p', 'A_', 'a_', 'Z_', 'B_', 'b_', 'H_', 'h_', 'u_', 'M_', 'm_', 'P_', 'p_'

Thanks.

Steven.

**Comment by jrm2194** [comment]
Sure. It shouldn't be too hard. Try this:

``` ruby
File.open(file_path, 'wb') do |file| 
  file.write(face_image['face_image'].pack('C*'))
end
```

It will work just fine ;)

**Comment by steview** [comment]
Hi

Thanks for your reply. Still no joy though :(

I tried:

``` ruby
File.open(file_path, 'wb') do |file|
    file.write(face_image['face_image'].pack('C*'))
end
```

I got:

NoMethodError: undefined method `unpack' for #Array:0x007fa3a023b8d8
Did you mean?  pack

I also tried (my code form before, with your new directive):

``` ruby
File.open(file_path, 'wb') do |file|
  file.write([face_image['face_image'].join].pack('C*'))
end
```

I got:

TypeError: no implicit conversion of String into Integer

Sorry, I know this isn't an issue with the gem, but I will be really grateful for any help.

Thanks.

Steven.

**Comment by jrm2194** [comment]
Hi Steview,

I believe I wrote `pack` in my little example below which is working fine for me :)

Please try to reproduce this pastee which is working juste fine:

https://pastee.org/p9b3c

**Comment by steview** [comment]
Hi @jrm2194 

I got it to work!

It seems an array of integers as strings.

My solution was:

``` ruby
File.open(file_path, 'wb') do |file|
  file.write(face_image['face_image'].map(&:to_i).pack('C*'))
end
```

I doubt it's the most efficient, but it does work.

I'm not going to try to work out why the API identified a shoe as a face!

Many thanks for your help.

Regards.

Steven.
